sudo: required
services:
  - docker

before_install:
  - docker build -t mwints/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mwints/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-eu-central-1-980554874121"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
